# Generated by Django 5.1 on 2024-09-08 05:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailconfirmationtoken_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
