# Generated by Django 5.1 on 2024-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdata_confirmed_userdata_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='time',
            field=models.PositiveIntegerField(default=7200),
        ),
    ]
