# Generated by Django 5.1 on 2024-10-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='time',
            field=models.PositiveIntegerField(default=900),
        ),
    ]
